In [1]:
import pandas as pd
dataset = pd.read_csv("50_Startups.csv")  # get fresh copy
dataset = pd.get_dummies(dataset, columns=['State'], dtype= int)
dataset

,R&D Spend,Administration,Marketing Spend,Profit,State_California,State_Florida,State_New York
0,165349.20,136897.80,471784.10,192261.83,0,0,1
1,162597.70,151377.59,443898.53,191792.06,1,0,0
2,153441.51,101145.55,407934.54,191050.39,0,1,0
3,144372.41,118671.85,383199.62,182901.99,0,0,1
4,142107.34,91391.77,366168.42,166187.94,0,1,0
5,131876.90,99814.71,362861.36,156991.12,0,0,1
6,134615.46,147198.87,127716.82,156122.51,1,0,0
7,130298.13,145530.06,323876.68,155752.60,0,1,0
8,120542.52,148718.95,311613.29,152211.77,0,0,1
9,123334.88,108679.17,304981.62,149759.96,1,0,0
10,101913.08,110594.11,229160.95,146121.95,0,1,0
11,100671.96,91790.61,249744.55,144259.40,1,0,0
12,93863.75,127320.38,249839.44,141585.52,0,1,0
13,91992.39,135495.07,252664.93,134307.35,1,0,0
14,119943.24,156547.42,256512.92,132602.65,0,1,0
15,114523.61,122616.84,261776.23,129917.04,0,0,1
16,78013.11,121597.55,264346.06,126992.93,1,0,0
17,94657.16,145077.58,282574.31,125370.37,0,0,1
18,91749.16,114175.79,294919.57,124266.90,0,1,0
19,86419.70,153514.11,0.00,122776.86,0,0,1
20,76253.86,113867.30,298664.47,118474.03,1,0,0
21,78389.47,153773.43,299737.29,111313.02,0,0,1
22,73994.56,122782.75,303319.26,110352.25,0,1,0
23,67532.53,105751.03,304768.73,108733.99,0,1,0
24,77044.01,99281.34,140574.81,108552.04,0,0,1
25,64664.71,139553.16,137962.62,107404.34,1,0,0
26,75328.87,144135.98,134050.07,105733.54,0,1,0
27,72107.60,127864.55,353183.81,105008.31,0,0,1
28,66051.52,182645.56,118148.20,103282.38,0,1,0
29,65605.48,153032.06,107138.38,101004.64,0,0,1
30,61994.48,115641.28,91131.24,99937.59,0,1,0
31,61136.38,152701.92,88218.23,97483.56,0,0,1
32,63408.86,129219.61,46085.25,97427.84,1,0,0
33,55493.95,103057.49,214634.81,96778.92,0,1,0
34,46426.07,157693.92,210797.67,96712.80,1,0,0
35,46014.02,85047.44,205517.64,96479.51,0,0,1
36,28663.76,127056.21,201126.82,90708.19,0,1,0
37,44069.95,51283.14,197029.42,89949.14,1,0,0
38,20229.59,65947.93,185265.10,81229.06,0,0,1
39,38558.51,82982.09,174999.30,81005.76,1,0,0
40,28754.33,118546.05,172795.67,78239.91,1,0,0
41,27892.92,84710.77,164470.71,77798.83,0,1,0
42,23640.93,96189.63,148001.11,71498.49,1,0,0
43,15505.73,127382.30,35534.17,69758.98,0,0,1
44,22177.74,154806.14,28334.72,65200.33,1,0,0
45,1000.23,124153.04,1903.93,64926.08,0,0,1
46,1315.46,115816.21,297114.46,49490.75,0,1,0
47,0.00,135426.92,0.00,42559.73,1,0,0
48,542.05,51743.15,0.00,35673.41,0,0,1
49,0.00,116983.80,45173.06,14681.40,1,0,0